name: snapshot_helper
description: A simple helper to manage widget output from the AsyncSnapshot of a stream.
version: 1.0.0
homepage: https://github.com/magicleon94/snapshot_helper

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
